version: "3"

services:
  web:
    image: php:7.3.8-fpm-alpine
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php artisan serve --host=0.0.0.0
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    volumes: 
      - ./app:/app